runtime: custom
env: flex

entrypoint: find ${VIRTUAL_ENV}/lib/python3.6/site-packages/streamlit -type f \( -iname \*.py -o -iname \*.js \) -print0 | xargs -0 sed -i 's/healthz/health-check/g' && streamlit run sim_v3.py --server.port $PORT --server.enableCORS=false

manual_scaling:
  instances: 1

network:
  session_affinity: true

resources:
  cpu: 2
  memory_gb: 5
  disk_size_gb: 20
